spring:
  application:
    name: api-gateway
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:microservices_db}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:CHANGE_THIS_SECURE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 50
      minimum-idle: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      leak-detection-threshold: 60000
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 50
          max-idle: 20
          min-idle: 5

server:
  port: 8080
  ssl:
    enabled: ${SSL_ENABLED:false}
  tomcat:
    threads:
      max: 200
      min-spare: 10
    max-connections: 8192
    accept-count: 100
    connection-timeout: 20000
  servlet:
    session:
      cookie:
        secure: false
        http-only: true
        same-site: strict
      timeout: 30m

jwt:
  secret: ${JWT_SECRET:YWJjZGVmZ2hpams7bG1ub3BxcnN0dXZ3eHl6MTIzNDU2Nzg5MGFiY2RlZmdoaWprO2xtbm9wcXJzdHV2eHl6MTIzNDU2Nzg5MA==}
  expiration: ${JWT_EXPIRATION:86400000}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION:604800000}

# Rate Limiting Configuration
rate-limit:
  requests-per-minute: ${RATE_LIMIT_REQUESTS_PER_MINUTE:300}
  burst-capacity: ${RATE_LIMIT_BURST_CAPACITY:500}

# Security Configuration
security:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:https://localhost:3000,https://localhost:8080}
  headers:
    content-security-policy: "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self'; connect-src 'self'; frame-ancestors 'none'"
    hsts-max-age: 31536000

gateway:
  accounts-service-url: ${ACCOUNTS_SERVICE_URL:http://localhost:8081}
  api-key: ${API_KEY:YWJjZGVmZ2hpams7bG1ub3BxcnN0dXZ3eHl6MTIzNDU2Nzg5MA==}

logging:
  level:
    com.microservices.gateway: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always