spring:
  application:
    name: api-gateway
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:microservices_db}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres123}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET:your-super-secret-jwt-key-change-in-production-make-it-long-and-random-this-is-a-very-long-secret-key-for-jwt-signing-that-is-secure-enough-for-production-use-and-should-be-at-least-256-bits-long}
  expiration: 86400000
  refresh-expiration: 604800000

gateway:
  accounts-service-url: ${ACCOUNTS_SERVICE_URL:http://localhost:8081}
  api-key: ${API_KEY:YWJjZGVmZ2hpams7bG1ub3BxcnN0dXZ3eHl6MTIzNDU2Nzg5MA==}

logging:
  level:
    com.microservices.gateway: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always