spring:
  application:
    name: accounts-service
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:microservices_db}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:CHANGE_THIS_SECURE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true

server:
  port: 8081

accounts:
  api-key: ${API_KEY:YWJjZGVmZ2hpams7bG1ub3BxcnN0dXZ3eHl6MTIzNDU2Nzg5MA==}
  max-response-time-ms: 200
  connection-pool-size: 20
  query-timeout-seconds: 5
  
security:
  sql-injection-protection:
    enabled: true
    log-attempts: true
    block-malicious-requests: true
    max-input-length: 1000
    allowed-special-chars: ".,-_()&"

logging:
  level:
    com.microservices.accounts: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      enabled: true
  security:
    enabled: false
  server:
    port: 8081